cataSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cata/', include("tecnicas.urls")),
    path('admin/', admin.site.urls),

    path("__reload__/", include("django_browser_reload.urls")),
]

cata_system/urls.py
from django.contrib import admin
from django.urls import path, include
from cata_system import views

urlpatterns = [
    path("", views.home, name="home"),
    path('cata/', include("tecnicas.urls")),
    path('admin/', admin.site.urls),

    path("__reload__/", include("django_browser_reload.urls")),
]

tecnicas/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name = "cata_system"
urlpatterns = [
    path("", views.mainPanel, name="index"),

    # Atentificacion
    path("autenticacion",
         views.autentication,
         name="autenticacion"),


    # Gestion de catadores
    path("panel-catadores",
         views.testerMenu,
         name="panel_catadores"),

    path("crear-catador",
         views.testerCreate,
         name="crear_catador"),

    path("buscar-catador",
         views.testerSearch,
         name="buscar_catador"),


    # Creacion de sessiones sensoriales
    path("seleccion-tecnica",
         views.selecionTecnica,
         name="seleccion_tecnica"),

    path("panel-configuracion-basic",
         views.configurationPanelBasic,
         name="panel_configuracion_basic"),

    path("panel-configuracion-tags",
         views.configurationPanelTags,
         name="panel_configuracion_tags"),

    path("panel-configuracion-codes",
         views.configurationPanelCodes,
         name="panel_configuracion_codes"),

    path("panel-configuracion-words",
         views.configurationPanelWords,
         name="panel_configuracion_words"),

    path("creando-sesion",
         views.createSession,
         name="creando_sesion"),


    # Gestion de sesiones sensoriales
    path("panel-sesiones/<int:page>",
         views.sesionsPanel,
         name="panel_sesiones"),

    path("detalles-sesion/<str:session_code>",
         views.sessionDetails,
         name="detalles_sesion"),


    # Vistas para catadores
    path("catador-login",
         views.testerLogin,
         name="catador_login"),

    path("testers/catador-main",
         views.mainTesterForm,
         name="catador_main"),

    # APIs
    path("nueva-etiqueta",
         views.newTag,
         name="nueva_etiqueta"),

    path("api/palabras",
         views.words,
         name="api_palabras"),
]

tecnicas/models/calificacion.py
from django.db import models

from .producto import Producto
from .tecnica import Tecnica
from .catador import Catador

class Calificacion(models.Model):
    num_repeticion = models.IntegerField()
    id_producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name="calificacion_producto")
    id_tecnica = models.ForeignKey(Tecnica, on_delete=models.CASCADE, related_name="calificacion_tecnica")
    id_catador = models.ForeignKey(Catador, on_delete=models.CASCADE, related_name="calificacion_catador")

tecnicas/models/catador.py
from django.db import models

class Catador(models.Model):
    usuarioCatador = models.CharField(max_length=255, unique=True)
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    telefono = models.BigIntegerField()
    correo = models.EmailField()
    fechaNacimiento = models.DateField()

    def __str__(self):
        return self.usuarioCatador

tecnicas/models/categoria_tecnica.py
from django.db import models

class CategoriaTecnica(models.Model):
    nombre_categoria = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.nombre_categoria

tecnicas/models/dato.py
from django.db import models

from .palabra import Palabra
from .calificacion import Calificacion

class Dato(models.Model):
    id_palabra = models.ForeignKey(Palabra, on_delete=models.CASCADE, related_name="dato_palabra")
    id_calificacion = models.ForeignKey(Calificacion, on_delete=models.CASCADE, related_name="dato_calificacion")

tecnicas/models/dato_valor.py
from django.db import models

from .dato import Dato

class ValorDecimal(models.Model):
    id_dato = models.OneToOneField(Dato, on_delete=models.CASCADE, related_name="dato_decimal")
    valor = models.FloatField()

    def __str__(self):
        return self.valor

class ValorBooleano(models.Model):
    id_dato = models.OneToOneField(Dato, on_delete=models.CASCADE, related_name="dato_boolean")
    valor = models.BooleanField()

    def __str__(self):
        return self.valor

tecnicas/models/es_atributo.py
from django.db import models

from .tecnica import Tecnica
from .palabra import Palabra

class EsAtributo(models.Model):
    id_tecnica = models.OneToOneField(Tecnica, on_delete=models.CASCADE, related_name="tecnica_esatributo")
    palabras = models.ManyToManyField(Palabra, related_name="estilo_atributo_palabras")

tecnicas/models/es_vocabulario.py
from django.db import models

from .tecnica import Tecnica
from .vocabulario import Vocabulario

class EsVocabulario(models.Model):
    id_tecnica = models.OneToOneField(Tecnica, on_delete=models.CASCADE, related_name="tecnica_esvacabulario")
    id_vocabulario = models.ForeignKey(Vocabulario, on_delete=models.CASCADE, related_name="vocabulario_esvocabulario")

tecnicas/models/escala.py
from django.db import models

from .tipo_escala import TipoEscala
from .tecnica import Tecnica

class Escala(models.Model):
    id_tipo_escala = models.ForeignKey(TipoEscala, on_delete=models.CASCADE, related_name="escala_tipo_escala")
    longitud = models.IntegerField()
    tecnica = models.OneToOneField(Tecnica, on_delete=models.CASCADE, related_name="escala_tecnica")

    def __str__(self):
        return self.id_tipo_escala.nombre_escala

tecnicas/models/estilo_palabra.py
from django.db import models

class EstiloPalabra(models.Model):
    nombre_estilo = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.nombre_estilo

tecnicas/models/etiqueta.py
from django.db import models

class Etiqueta(models.Model):
    valor_etiqueta = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.valor_etiqueta

tecnicas/models/etiquetas_escala.py
from django.db import models
from .escala import Escala
from .etiqueta import Etiqueta


class EtiquetasEscala(models.Model):
    id_escala = models.ForeignKey(
        Escala, on_delete=models.CASCADE, related_name="escalas_etiqutas_escala")

    id_etiqueta = models.ForeignKey(
        Etiqueta, on_delete=models.CASCADE, related_name="etiqueta_etiquetas_escala")

    posicion = models.IntegerField()

    def __str__(self):
        return f"Escala {self.id_escala.id}, {self.id_etiqueta.valor_etiqueta}, posicion {self.posicion}"

tecnicas/models/orden.py
from django.db import models

from .tecnica import Tecnica
from .catador import Catador
from .producto import Producto

class Orden(models.Model):
    id_tecnica = models.ForeignKey(Tecnica, on_delete=models.CASCADE, related_name="orden_tecnica")
    id_catador = models.ForeignKey(Catador, on_delete=models.CASCADE, related_name="orden_catador", null=True)

    def __str__(self):
        return f"Orden ID: {self.id}"

class Posicion(models.Model):
    id_producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name="posicion_producto")
    id_orden = models.ForeignKey(Orden, on_delete=models.CASCADE, related_name="posicion_orden")
    posicion = models.IntegerField()

    def __str__(self):
        return f"Posicion ID: {self.id}"

tecnicas/models/palabra.py
from django.db import models


class Palabra(models.Model):
    nombre_palabra = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.nombre_palabra

    def to_dict(self):
        return {
            "id": self.id,
            "nombre_palabra": self.nombre_palabra
        }

tecnicas/models/participacion.py
from django.db import models
from .tecnica import Tecnica
from .catador import Catador


class Participacion(models.Model):
    tecnica = models.ForeignKey(
        Tecnica, on_delete=models.CASCADE, related_name="tecnica_participacion")
    catador = models.ForeignKey(
        Catador, on_delete=models.CASCADE, related_name="catador_participacion")
    activo = models.BooleanField(default=False)
    finalizado = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.catador.usuarioCatador} {'activo' if self.activo else 'no activo'}"

tecnicas/models/presentador.py
from django.db import models

class Presentador(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    nombre_usuario = models.CharField(max_length=255, unique=True)
    contrasena = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

tecnicas/models/producto.py
from django.db import models

from .tecnica import Tecnica

class Producto(models.Model):
    codigoProducto = models.CharField(max_length=3)
    id_tecnica = models.ForeignKey(Tecnica, on_delete=models.CASCADE, related_name="producto_tecnica")

    def __str__(self):
        return self.codigoProducto

tecnicas/models/sesion_sensorial.py
from django.db import models
from django.utils import timezone
from .presentador import Presentador
from .tecnica import Tecnica
import shortuuid


class SesionSensorial(models.Model):
    codigo_sesion = models.CharField(
        primary_key=True, default=shortuuid.uuid, editable=False, max_length=22)
    nombre_sesion = models.CharField(max_length=255, null=True)
    fechaCreacion = models.DateTimeField(default=timezone.now)
    activo = models.BooleanField(default=False)
    creadoPor = models.ForeignKey(
        Presentador, on_delete=models.CASCADE, related_name="presentador_sesion")
    tecnica = models.OneToOneField(
        Tecnica, on_delete=models.CASCADE, related_name="sesion_tecnica")

    def __str__(self):
        return self.nombre_sesion if self.nombre_sesion else self.codigo_sesion

tecnicas/models/tecnica.py
from django.db import models

from .estilo_palabra import EstiloPalabra
from .tipo_tecnica import TipoTecnica


class Tecnica(models.Model):
    tipo_tecnica = models.ForeignKey(
        TipoTecnica, on_delete=models.CASCADE, related_name="tecnica_tipo_tecnica")
    repeticiones_max = models.IntegerField(default=0)
    repecion = models.IntegerField(default=0)
    limite_catadores = models.IntegerField()
    instrucciones = models.CharField(max_length=255)
    id_estilo = models.ForeignKey(
        EstiloPalabra, on_delete=models.CASCADE, related_name="estilo_tecnica")

    def __str__(self):
        return f"{self.id} : {self.tipo_tecnica.nombre_tecnica} : {self.id_estilo.nombre_estilo}"

    def toDict(self):
        return {
            "tipo_tecnica": self.tipo_tecnica,
            "repeticiones_max": self.repeticiones_max,
            "repecion": self.repecion,
            "limite_catadores": self.limite_catadores,
            "instrucciones": self.instrucciones,
            "id_estilo": self.id_estilo,
        }

tecnicas/models/tipo_escala.py
from django.db import models

class TipoEscala(models.Model):
    nombre_escala = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre_escala

tecnicas/models/tipo_tecnica.py
from django.db import models

from .categoria_tecnica import CategoriaTecnica

class TipoTecnica(models.Model):
    nombre_tecnica = models.CharField(max_length=255, unique=True)
    id_categoria_tecnica = models.ForeignKey(CategoriaTecnica, on_delete=models.CASCADE, related_name="tipo_tecnica_categoria_tecnica")

    def __str__(self):
        return self.nombre_tecnica

tecnicas/templates/tecnicas/catador-buscar.html
{% extends 'tecnicas/base.html' %}
{% load static %}

{% block title %}Buscar Catador{% endblock %}

{% block content %}
<article class="w-full flex flex-col justify-center items-center bg-gray-600 my-10">
    <article class="flex flex-col gap-4 bg-gray-400 md:p-10 p-5 rounded-2xl lg:w-4xl w-full">
        <header class="flex-1 flex flex-col gap-7">
            <div class="bg-gray-300 p-8 text-2xl font-bold rounded-2xl text-center capitalize">
                <h1>buscando catatador</h1>
            </div>
        </header>
        <form action="" method="get" class="flex flex-col gap-5">
            <h2 class="text-2xl mb-2 font-bold">Ingrese el nombre de usuario del catador</h2>
            <section class="">
                <label for="usuario" class="text-lg flex flex-col px-2 w-full font-medium tracking-wide mb-4">
                    <div class="flex flex-wrap gap-4 justify-center items-center">
                        <p class="capitalize font-bold">nombre de usuario:</p>
                        <input id="usuario" type="text" class="bg-gray-500 text-center w-fit p-1 rounded-lg text-white"
                            name="user" required>
                        <button type="submit"
                            class="uppercase text-lg tracking-wider font-medium p-2 px-4 border-b-2 active:border-b-0 active:border-t-2 border-green-800  transition-all rounded-xl bg-green-600 active:bg-green-400 text-white w-fit">
                            buscar
                        </button>
                        <a href="{% url 'cata_system:panel_catadores' %}"
                            class="uppercase text-lg tracking-wider font-medium p-2 px-4 border-b-2 active:border-b-0 active:border-t-2 border-yellow-800  transition-all rounded-xl bg-yellow-600 active:bg-yellow-400 text-white w-fit">
                            regresar
                        </a>
                    </div>
                    {% if catador.errors %}
                    <small class="capitalize bg-red-400 px-5 tracking-wider rounded">
                        {{ catador.errors }}
                    </small>
                    {% endif %}
                </label>
            </section>
        </form>
        {% if error %}
        <p class="ct-notifica bg-red-500 text-center text-lg py-1 font-bold text-white tracking-wide capitalize rounded-2xl">
            {{ error }}
        </p>
        {% endif %}

        {% if message %}
        <p class="ct-notifica bg-green-600 text-center text-lg py-1 font-bold text-white tracking-wide capitalize rounded-2xl">
            {{ message }}
        </p>
        {% endif %}
        
        {% if form_catador %}
        <form action="" method="post">
            {% csrf_token %}
            <section class="grid grid-cols-2 max-sm:grid-cols-1 [&>label]:px-6 max-sm:[&>label]:px-2">
                <label for="{{ form_catador.usuarioCatador.id_for_label }}"
                    class="text-lg flex flex-col px-2 w-full font-medium tracking-wide mb-4">
                    <p class="capitalize font-bold">Nombre de usuario:</p>
                    {{ form_catador.usuarioCatador }}
                    {% if form_catador.usuarioCatador.errors %}
                    <small class="capitalize bg-red-400 px-5 tracking-wider rounded">
                        el nombre de usuario ya esta en uso
                    </small>
                    {% endif %}
                </label>
                <label for="{{ form_catador.nombre.id_for_label }}"
                    class="text-lg flex flex-col px-2 w-full font-medium tracking-wide mb-4">
                    <p class="capitalize font-bold">nombre del catador:</p>
                    {{ form_catador.nombre }}
                </label>
                <label for="{{ form_catador.apellido.id_for_label }}"
                    class="text-lg flex flex-col px-2 w-full font-medium tracking-wide mb-4">
                    <p class="capitalize font-bold">apellido del catador:</p>
                    {{ form_catador.apellido }}
                </label>
                <label for="{{ form_catador.telefono.id_for_label }}"
                    class="text-lg flex flex-col px-2 w-full font-medium tracking-wide mb-4">
                    <p class="capitalize font-bold">telefono:</p>
                    {{ form_catador.telefono }}
                    {% if form_catador.telefono.errors %}
                    <small class="ct-notificacion capitalize bg-red-400 px-5 tracking-wider rounded">
                        {{ form_catador.telefono.errors}}
                    </small>
                    {% endif %}
                </label>
                <label for="{{ form_catador.correo.id_for_label }}"
                    class="text-lg flex flex-col px-2 w-full font-medium tracking-wide mb-4">
                    <p class="capitalize font-bold">correo:</p>
                    {{ form_catador.correo }}
                </label>
                <label for="{{ form_catador.fechaNacimiento.id_for_label }}"
                    class="text-lg flex flex-col px-2 w-full font-medium tracking-wide mb-4">
                    <p class="capitalize font-bold">fecha de nacimiento:</p>
                    {{ form_catador.fechaNacimiento }}
                </label>
            </section>
            <section class="cs-escalas-radio flex justify-center items-center gap-4">
                <button type="button"
                    class="ct-btn-actualizar uppercase text-lg tracking-wider font-medium p-2 px-4 border-b-2 active:border-b-0 active:border-t-2 border-purple-800  transition-all rounded-xl bg-purple-600 active:bg-purple-400 text-white w-fit"
                    onclick="enableInputs()">
                    actualizar
                </button>
                <button type="submit"
                    class="ct-btn-guardar uppercase text-lg tracking-wider font-medium p-2 px-4 border-b-2 active:border-b-0 active:border-t-2 border-green-800  transition-all rounded-xl bg-green-600 active:bg-green-400 text-white w-fit hidden">
                    guardar
                </button>
                <button type="button"
                    class="ct-btn-cancel uppercase text-lg tracking-wider font-medium p-2 px-4 border-b-2 active:border-b-0 active:border-t-2 border-yellow-800  transition-all rounded-xl bg-yellow-600 active:bg-yellow-400 text-white w-fit hidden"
                    onclick="changeButtons(disableInputs)">
                    cancelar
                </button>
            </section>
        </form>
        {% endif %}
    </article>
</article>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/catador-search.js' %}"></script>
{% endblock %}

tecnicas/templates/tecnicas/catadores-panel.html
{% extends 'tecnicas/base.html' %}
{% load static %}

{% block title %}Gestionar Catadores{% endblock %}

{% block content %}
<article class="w-full h-full flex flex-col justify-center items-center bg-gray-600">
    <article class="flex flex-row gap-8 bg-gray-400 p-10 rounded-2xl w-3xl">
        <header class="flex-1 flex flex-col gap-7">
            <div class="bg-gray-300 p-8 text-2xl font-bold rounded-2xl text-center">
                <h1>Adiministra los<br>catadores aquí</h1>
            </div>
            <a href="{% url 'cata_system:index' %}"
                class="text-white bg-blue-600 hover:bg-blue-700 active:outline-none active:ring-4 active:ring-blue-300 font-medium rounded-xl text-xl p-4 text-center uppercase">Panel
                principal</a>
            <div class="w-full h-60 bg-gray-200 rounded-2xl relative">
                <img src="{% static 'img/pn_gc_test.webp' %}" alt="un hombre en smokin probando vino"
                    class="h-full w-full object-cover rounded-xl">
            </div>
        </header>
        <section class="flex-1 flex flex-col gap-7">
            <div class="w-full h-40 rounded-2xl">
                <img src="{% static 'img/pn_gc_people.webp' %}" alt="varias personas en fila"
                    class="w-full h-full object-cover rounded-xl">
            </div>
            <a class="flex-1 text-white tracking-wider font-bold bg-green-600 border-green-800 border-r-4 border-b-4 active:border-r-0 active:border-b-0 active:border-t-4 active:border-l-4 transition-all rounded-xl text-xl p-4 flex justify-center items-center uppercase"
                href="{% url 'cata_system:crear_catador' %}">
                Crear Cadator
            </a>
            <a href="{% url 'cata_system:buscar_catador' %}"
                class="flex-1 text-white tracking-wider font-bold bg-yellow-600 border-yellow-800 border-r-4 border-b-4 active:border-r-0 active:border-b-0 active:border-t-4 active:border-l-4 transition-all rounded-xl text-xl p-4 flex justify-center items-center uppercase">
                Buscar Catador
            </a>
        </section>
    </article>
</article>
{% endblock %}

tecnicas/templates/tecnicas/main-panel.html
{% extends 'tecnicas/layouts/base.html' %}

{% block title %}Panel principal{% endblock %}

{% block content %}
<article class="w-full h-full flex flex-col justify-center items-center bg-gray-600">
    <h1 class="text-4xl font-bold text-center max-sm:hidden">Panel Principal</h1>

    <article class="w-full flex flex-col gap-7 items-center mt-7">
        <article
            class="w-5xl max-lg:w-3xl max-md:w-auto p-8 flex flex-row flex-wrap justify-center items-center gap-8 bg-zinc-400 rounded-md">
            <section class="flex flex-col text-white flex-1 flex-wrap gap-4">
                <fieldset class="fieldset rounded-box border px-3 pb-3 rounded-2xl">
                    <legend class="fieldset-legend px-1.5">Nombre</legend>
                    <p class="text-3xl font-medium">{{ presentador.nombre }}</p>
                </fieldset>
                <fieldset class="fieldset rounded-box border px-3 pb-3 rounded-2xl">
                    <legend class="fieldset-legend px-1.5">Identificador</legend>
                    <p class="text-3xl font-medium">{{ presentador.id }}</p>
                </fieldset>
            </section>
            <section class="flex-1 flex justify-center">
                <button type="button"
                    class="text-white bg-red-600 hover:bg-red-700 active:outline-none active:ring-4 active:ring-red-300 font-medium rounded-2xl text-3xl px-5 py-4 text-center uppercase">Salir
                    del sistema</button>
            </section>
        </article>

        <article
            class="w-5xl max-lg:w-3xl max-md:w-auto p-8 flex flex-col justify-around items-center gap-4 flex-wrap bg-zinc-400 rounded-md">
            <section class="flex flex-row flex-wrap gap-4 w-full">
                <a href="{% url 'cata_system:seleccion_tecnica' %}"
                    class="text-white bg-green-600 hover:bg-green-700 active:outline-none active:ring-4 active:ring-green-300 font-medium rounded-xl text-3xl px-8 py-4 text-center uppercase flex-1">Iniciar
                    Sesión <br> Sensorial</a>
                <a href="{% url 'cata_system:panel_catadores' %}"
                    class="text-white bg-yellow-600 hover:bg-yellow-700 active:outline-none active:ring-4 active:ring-yellow-300 font-medium rounded-xl text-3xl px-8 py-4 text-center uppercase flex-1">Gestión
                    de <br>catadores</a>
            </section>

            <section class="flex flex-row flex-wrap gap-4 w-f ull justify-center">
                <a href="{% url 'cata_system:panel_sesiones' page=1 %}"
                    class="text-white bg-blue-600 hover:bg-blue-700 active:outline-none active:ring-4 active:ring-blue-300 font-medium rounded-xl text-3xl px-8 py-4 text-center uppercase">Gestión
                    de sesiones <br> sensoriales</a>
            </section>
        </article>
    </article>
</article>
{% endblock %}

tecnicas/templates/tecnicas/seleccion-tecnica.html
{% extends 'tecnicas/base.html' %}

{% block title %}Panel principal{% endblock %}

{% block content %}
<article class="w-full flex flex-col justify-center items-center bg-gray-600 mt-10 mb-10">
    <article class="flex flex-col gap-8 bg-gray-400 md:p-10 p-5 rounded-2xl lg:w-4xl w-full">
        <header class="text-center flex sm:flex-row flex-col md:gap-8 gap-3 items-center w-full">
            <div class="bg-gray-600 p-4 text-white rounded-xl sm:flex-1 w-full">
                <h1 class="font-bold text-2xl">Selección de<br>técnica sensorial</h1>
            </div>
            <div class="sm:flex-1 flex flex-row-reverse">
                <a href="{% url 'cata_system:index' %}"
                    class="text-white bg-blue-600 hover:bg-blue-700 active:outline-none active:ring-4 active:ring-blue-300 font-medium rounded-xl text-xl p-4 text-center uppercase">Panel
                    principal</a>
            </div>
        </header>
        <section class="text-white *:not-last:mb-4">
            {% if error %}
            <article class="ct-error bg-red-400 rounded-xl text-center font-normal tracking-wider text-xl p-1 pb-2">
                <p>{{ error }}</p>
            </article>
            {% endif %}

            {% for cate, tecnicas in tipos.items %}
            <article>
                <button
                    class="p-4 bg-blue-700 hover:bg-blue-800 active:ring-4 active:outline-none active:ring-blue-300 flex flex-row gap-4 justify-center items-center rounded-lg text-2xl font-medium uppercase tracking-wider w-full z-20 relative"
                    onclick="showList('{{cate}}'); hiddenError()" type="button">{{ cate }}</button>
                {% if tecnicas %}
                <section
                    class="modal-list-{{ cate }} flex flex-col text-lg bg-blue-100 p-4 pr-6 pl-8 sm:pl-12 z-10 -translate-y-1 rounded-b-2xl *:not-last:mb-4 transition-all duration-1000 hidden w-full">
                    {% for tecnica in tecnicas %}
                    <a href="{% url 'cata_system:panel_configuracion_basic'%}?id_tecnica={{tecnica.id}}"
                        class="bg-green-700 border-l-10 border-gray-700 rounded-md px-3 py-2 w-full font-bold tracking-wider text-left uppercase">
                        {{ tecnica.nombre_tecnica }}
                    </a>
                    {% endfor %}
                </section>
                {% endif %}
            </article>
            {% endfor %}
        </section>
    </article>
</article>
{% endblock %}

{% block extra_js %}
<script>
    function showList (name) {
        name = ".modal-list-" + name
        const list = document.querySelector(name)
        if (list.classList.contains("hidden")) {
            list.classList.remove("hidden")
        } else {
            list.classList.add("hidden")
        }
    }

    function hiddenError () {
        const error = document.getElementsByClassName("ct-error")[0]
        error.classList.add("hidden")
    }
</script>
{% endblock %}

tecnicas/templates/tecnicas/sesiones-panel.html
{% extends 'tecnicas/base.html' %}
{% load static %}

{% block title %}Panel Sesiones{% endblock %}

{% block content %}
<article class="w-full flex flex-col justify-center items-center bg-gray-600 mt-10 mb-10">
    <article class="flex flex-col gap-8 bg-gray-400 p-10 rounded-2xl w-4xl">
        <header class="text-center flex flex-row gap-8 items-center w-full">
            <div class="bg-gray-600 p-4 text-white rounded-xl flex-1">
                <h1 class="font-bold text-2xl">Administra las<br>sesiones sensoriales</h1>
            </div>
            <div class="flex-1">
                <a href="{% url 'cata_system:index' %}"
                    class="text-white bg-blue-600 hover:bg-blue-700 active:outline-none active:ring-4 active:ring-blue-300 font-medium rounded-xl text-xl p-4 text-center uppercase">Panel
                    principal</a>
            </div>
        </header>
        <section class="grid grid-cols-3 gap-4">
            <article class="p-4 bg-gray-200 flex flex-row gap-4 justify-center items-center rounded-lg">
                <div class="text-right *:not-last:mb-4">
                    <p><b>Código:</b></p>
                    <p><b>Fecha:</b></p>
                    <p><b>Técnica:</b></p>
                </div>
                <div class="*:not-last:mb-4">
                    <p>9J78GGHJK7V</p>
                    <p>12-07-2025</p>
                    <p>Intensidad</p>
                </div>
            </article>

            {% for elem in elementos %}
            <article class="p-4 bg-gray-200 flex flex-row gap-4 justify-center items-center rounded-lg">
                <div class="text-right *:not-last:mb-4">
                    <p><b>Código:</b></p>
                    <p><b>Fecha:</b></p>
                    <p><b>Técnica:</b></p>
                </div>
                <div class="*:not-last:mb-4">
                    <p>{{ elem.nombre }}</p>
                    <p>{{ elem.fecha }}</p>
                    <p>{{ elem.tecnica }}</p>
                </div>
            </article>
            {% endfor %}
        </section>
        <section class="flex justify-center items-center gap-2">
            <button>
                <img class="h-10" src="{% static 'img/less-than.svg' %}" alt="menor que">
            </button>
            <ul class="flex flex-row gap-2">
                <li>1</li>
                <li>2</li>
                <li>3</li>
                <li>. . .</li>
                <li>8</li>
            </ul>
            <button>
                <img class="h-10" src="{% static 'img/greater-than.svg' %}" alt="mayor que">
            </button>
        </section>
    </article>
</article>
{% endblock %}