cataSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cata/', include("tecnicas.urls")),
    path('admin/', admin.site.urls),

    path("__reload__/", include("django_browser_reload.urls")),
]

cata_system/urls.py
from django.contrib import admin
from django.urls import path, include
from cata_system import views

urlpatterns = [
    path("", views.home, name="home"),
    path('cata/', include("tecnicas.urls")),
    path('admin/', admin.site.urls),

    path("__reload__/", include("django_browser_reload.urls")),
]

tecnicas/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name = "cata_system"
urlpatterns = [
    path("", views.mainPanel, name="index"),

    # Atentificacion
    path("autenticacion",
         views.autentication,
         name="autenticacion"),


    # Gestion de catadores
    path("panel-catadores",
         views.testerMenu,
         name="panel_catadores"),

    path("crear-catador",
         views.testerCreate,
         name="crear_catador"),

    path("buscar-catador",
         views.testerSearch,
         name="buscar_catador"),


    # Creacion de sessiones sensoriales
    path("seleccion-tecnica",
         views.selecionTecnica,
         name="seleccion_tecnica"),

    path("panel-configuracion-basic",
         views.configurationPanelBasic,
         name="panel_configuracion_basic"),

    path("panel-configuracion-tags",
         views.configurationPanelTags,
         name="panel_configuracion_tags"),

    path("panel-configuracion-codes",
         views.configurationPanelCodes,
         name="panel_configuracion_codes"),

    path("panel-configuracion-words",
         views.configurationPanelWords,
         name="panel_configuracion_words"),

    path("creando-sesion",
         views.createSession,
         name="creando_sesion"),


    # Gestion de sesiones sensoriales
    path("panel-sesiones/<int:page>",
         views.sesionsPanel,
         name="panel_sesiones"),

    path("detalles-sesion/<str:session_code>",
         views.sessionDetails,
         name="detalles_sesion"),


    # Vistas para catadores
    path("catador-login",
         views.testerLogin,
         name="catador_login"),

    path("testers/catador-main",
         views.mainTesterForm,
         name="catador_main"),

    # APIs
    path("nueva-etiqueta",
         views.newTag,
         name="nueva_etiqueta"),

    path("api/palabras",
         views.words,
         name="api_palabras"),
]

tecnicas/models/calificacion.py
from django.db import models

from .producto import Producto
from .tecnica import Tecnica
from .catador import Catador

class Calificacion(models.Model):
    num_repeticion = models.IntegerField()
    id_producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name="calificacion_producto")
    id_tecnica = models.ForeignKey(Tecnica, on_delete=models.CASCADE, related_name="calificacion_tecnica")
    id_catador = models.ForeignKey(Catador, on_delete=models.CASCADE, related_name="calificacion_catador")

tecnicas/models/catador.py
from django.db import models

class Catador(models.Model):
    usuarioCatador = models.CharField(max_length=255, unique=True)
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    telefono = models.BigIntegerField()
    correo = models.EmailField()
    fechaNacimiento = models.DateField()

    def __str__(self):
        return self.usuarioCatador

tecnicas/models/categoria_tecnica.py
from django.db import models

class CategoriaTecnica(models.Model):
    nombre_categoria = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.nombre_categoria

tecnicas/models/dato.py
from django.db import models

from .palabra import Palabra
from .calificacion import Calificacion

class Dato(models.Model):
    id_palabra = models.ForeignKey(Palabra, on_delete=models.CASCADE, related_name="dato_palabra")
    id_calificacion = models.ForeignKey(Calificacion, on_delete=models.CASCADE, related_name="dato_calificacion")

tecnicas/models/dato_valor.py
from django.db import models

from .dato import Dato

class ValorDecimal(models.Model):
    id_dato = models.OneToOneField(Dato, on_delete=models.CASCADE, related_name="dato_decimal")
    valor = models.FloatField()

    def __str__(self):
        return self.valor

class ValorBooleano(models.Model):
    id_dato = models.OneToOneField(Dato, on_delete=models.CASCADE, related_name="dato_boolean")
    valor = models.BooleanField()

    def __str__(self):
        return self.valor

tecnicas/models/es_atributo.py
from django.db import models

from .tecnica import Tecnica
from .palabra import Palabra

class EsAtributo(models.Model):
    id_tecnica = models.OneToOneField(Tecnica, on_delete=models.CASCADE, related_name="tecnica_esatributo")
    palabras = models.ManyToManyField(Palabra, related_name="estilo_atributo_palabras")

tecnicas/models/es_vocabulario.py
from django.db import models

from .tecnica import Tecnica
from .vocabulario import Vocabulario

class EsVocabulario(models.Model):
    id_tecnica = models.OneToOneField(Tecnica, on_delete=models.CASCADE, related_name="tecnica_esvacabulario")
    id_vocabulario = models.ForeignKey(Vocabulario, on_delete=models.CASCADE, related_name="vocabulario_esvocabulario")

tecnicas/models/escala.py
from django.db import models

from .tipo_escala import TipoEscala
from .tecnica import Tecnica

class Escala(models.Model):
    id_tipo_escala = models.ForeignKey(TipoEscala, on_delete=models.CASCADE, related_name="escala_tipo_escala")
    longitud = models.IntegerField()
    tecnica = models.OneToOneField(Tecnica, on_delete=models.CASCADE, related_name="escala_tecnica")

    def __str__(self):
        return self.id_tipo_escala.nombre_escala

tecnicas/models/estilo_palabra.py
from django.db import models

class EstiloPalabra(models.Model):
    nombre_estilo = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.nombre_estilo

tecnicas/models/etiqueta.py
from django.db import models

class Etiqueta(models.Model):
    valor_etiqueta = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.valor_etiqueta

tecnicas/models/etiquetas_escala.py
from django.db import models
from .escala import Escala
from .etiqueta import Etiqueta


class EtiquetasEscala(models.Model):
    id_escala = models.ForeignKey(
        Escala, on_delete=models.CASCADE, related_name="escalas_etiqutas_escala")

    id_etiqueta = models.ForeignKey(
        Etiqueta, on_delete=models.CASCADE, related_name="etiqueta_etiquetas_escala")

    posicion = models.IntegerField()

    def __str__(self):
        return f"Escala {self.id_escala.id}, {self.id_etiqueta.valor_etiqueta}, posicion {self.posicion}"

tecnicas/models/orden.py
from django.db import models

from .tecnica import Tecnica
from .catador import Catador
from .producto import Producto

class Orden(models.Model):
    id_tecnica = models.ForeignKey(Tecnica, on_delete=models.CASCADE, related_name="orden_tecnica")
    id_catador = models.ForeignKey(Catador, on_delete=models.CASCADE, related_name="orden_catador", null=True)

    def __str__(self):
        return f"Orden ID: {self.id}"

class Posicion(models.Model):
    id_producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name="posicion_producto")
    id_orden = models.ForeignKey(Orden, on_delete=models.CASCADE, related_name="posicion_orden")
    posicion = models.IntegerField()

    def __str__(self):
        return f"Posicion ID: {self.id}"

tecnicas/models/palabra.py
from django.db import models


class Palabra(models.Model):
    nombre_palabra = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.nombre_palabra

    def to_dict(self):
        return {
            "id": self.id,
            "nombre_palabra": self.nombre_palabra
        }

tecnicas/models/participacion.py
from django.db import models
from .tecnica import Tecnica
from .catador import Catador


class Participacion(models.Model):
    tecnica = models.ForeignKey(
        Tecnica, on_delete=models.CASCADE, related_name="tecnica_participacion")
    catador = models.ForeignKey(
        Catador, on_delete=models.CASCADE, related_name="catador_participacion")
    activo = models.BooleanField(default=False)
    finalizado = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.catador.usuarioCatador} {'activo' if self.activo else 'no activo'}"

tecnicas/models/presentador.py
from django.db import models

class Presentador(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    nombre_usuario = models.CharField(max_length=255, unique=True)
    contrasena = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

tecnicas/models/producto.py
from django.db import models

from .tecnica import Tecnica

class Producto(models.Model):
    codigoProducto = models.CharField(max_length=3)
    id_tecnica = models.ForeignKey(Tecnica, on_delete=models.CASCADE, related_name="producto_tecnica")

    def __str__(self):
        return self.codigoProducto

tecnicas/models/sesion_sensorial.py
from django.db import models
from django.utils import timezone
from .presentador import Presentador
from .tecnica import Tecnica
import shortuuid


class SesionSensorial(models.Model):
    codigo_sesion = models.CharField(
        primary_key=True, default=shortuuid.uuid, editable=False, max_length=22)
    nombre_sesion = models.CharField(max_length=255, null=True)
    fechaCreacion = models.DateTimeField(default=timezone.now)
    activo = models.BooleanField(default=False)
    creadoPor = models.ForeignKey(
        Presentador, on_delete=models.CASCADE, related_name="presentador_sesion")
    tecnica = models.OneToOneField(
        Tecnica, on_delete=models.CASCADE, related_name="sesion_tecnica")

    def __str__(self):
        return self.nombre_sesion if self.nombre_sesion else self.codigo_sesion

tecnicas/models/tecnica.py
from django.db import models

from .estilo_palabra import EstiloPalabra
from .tipo_tecnica import TipoTecnica


class Tecnica(models.Model):
    tipo_tecnica = models.ForeignKey(
        TipoTecnica, on_delete=models.CASCADE, related_name="tecnica_tipo_tecnica")
    repeticiones_max = models.IntegerField(default=0)
    repecion = models.IntegerField(default=0)
    limite_catadores = models.IntegerField()
    instrucciones = models.CharField(max_length=255)
    id_estilo = models.ForeignKey(
        EstiloPalabra, on_delete=models.CASCADE, related_name="estilo_tecnica")

    def __str__(self):
        return f"{self.id} : {self.tipo_tecnica.nombre_tecnica} : {self.id_estilo.nombre_estilo}"

    def toDict(self):
        return {
            "tipo_tecnica": self.tipo_tecnica,
            "repeticiones_max": self.repeticiones_max,
            "repecion": self.repecion,
            "limite_catadores": self.limite_catadores,
            "instrucciones": self.instrucciones,
            "id_estilo": self.id_estilo,
        }

tecnicas/models/tipo_escala.py
from django.db import models

class TipoEscala(models.Model):
    nombre_escala = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre_escala

tecnicas/models/tipo_tecnica.py
from django.db import models

from .categoria_tecnica import CategoriaTecnica

class TipoTecnica(models.Model):
    nombre_tecnica = models.CharField(max_length=255, unique=True)
    id_categoria_tecnica = models.ForeignKey(CategoriaTecnica, on_delete=models.CASCADE, related_name="tipo_tecnica_categoria_tecnica")

    def __str__(self):
        return self.nombre_tecnica

tecnicas/templates/tecnicas/manage_sesions/detalles-sesion.html
{% extends 'tecnicas/layouts/base.html' %}
{% load static %}

{% block title %}Detalles Sesion{% endblock %}

{% block content %}
<article class="w-full flex flex-col justify-center items-center bg-gray-600 mt-10 mb-10">
    <article class="flex flex-col gap-8 bg-gray-400 p-10 rounded-2xl">
        <header class="text-center flex-row w-full flex justify-around items-center flex-wrap gap-10">
            <h1 class="text-white rounded-xl font-bold text-2xl bg-gray-600 p-4 flex-1">
                Detalles de la sesión
            </h1>
            <a href="{% url 'cata_system:index' %}">
                <p
                    class="uppercase text-lg tracking-wider font-medium p-2 px-4 border-b-2 active:border-b-0 active:border-t-2 active:border-blue-500 border-blue-800  transition-all rounded-xl bg-blue-600 text-white">
                    Panel principal
                </p>
            </a>
        </header>

        {% if error %}
        <article class="bg-red-600 p-4 text-white rounded-xl ct-notification-error">
            <p class="block font-sans text-white text-xl antialiased font-bold uppercase tracking-wider text-center">
                {{ error }}
            </p>
        </article>
        {% endif %}

        {% if message %}
        <article class="bg-green-600 p-4 text-white rounded-xl ct-notification-error">
            <p class="block font-sans text-white text-xl antialiased font-bold uppercase tracking-wider text-center">
                {{ message }}
            </p>
        </article>
        {% endif %}

        <p class="font-bold text-2xl border-b-2">
            Información general
        </p>
        <article
            class="text-white rounded-xl grid grid-cols-2 max-sm:grid-cols-1 gap-3 *:bg-gray-500 *:flex *:flex-wrap *:items-center *:justify-center *:max-sm:justify-normal *:gap-x-2 *:p-4 *:rounded-2xl">
            <section class="col-span-2 max-sm:col-span-1">
                <p class="text-xl font-bold">
                    Código:
                </p>
                <p class="font-sans text-xl font-normal">
                    {{ sesion.codigo_sesion }}
                </p>
            </section>

            <section class="col-span-2 max-sm:col-span-1">
                <p class="text-xl font-bold">
                    Nombre:
                </p>
                <p class="text-xl antialiased">
                    {% if sesion.nombre_sesion %}
                    {{ sesion.nombre_sesion }}
                    {% else %}
                    Sin nombre
                    {% endif %}
                </p>
            </section>

            <section>
                <p class="text-xl font-medium">
                    Fecha creación:
                </p>
                <p class="font-sans text-lg font-normal uppercase">
                    {{ sesion.fechaCreacion }}
                </p>
            </section>

            <section>
                <p class="text-lg font-bold">
                    Estado:
                </p>
                <p class="font-sans text-lg font-normal">
                    {% if sesion.activo %}
                    En proceso
                    {% else %}
                    Listo para iniciar repetición
                    {% endif %}
                </p>
            </section>

            <section>
                <p class="text-xl font-medium">
                    Estilo palabras:
                </p>
                <p class="font-sans text-lg font-normal uppercase">
                    {{ sesion.tecnica.id_estilo }}
                </p>
            </section>

            <section>
                <p class="text-xl font-medium">
                    Técnica:
                </p>
                <p class="font-sans text-lg font-normal uppercase">
                    {{ sesion.tecnica.tipo_tecnica }}
                </p>
            </section>

            <section>
                <p class="text-xl font-medium">
                    Rep. Hechas:
                </p>
                <p class="font-sans text-lg font-normal">
                    {{ sesion.tecnica.repecion }}
                </p>
            </section>

            <section>
                <p class="text-xl font-medium">
                    Rep. Max:
                </p>
                <p class="font-sans text-lg font-normal">
                    {{ sesion.tecnica.repeticiones_max }}
                </p>
            </section>

            <section class="col-span-2 max-sm:col-span-1">
                <p class="text-xl font-bold">
                    Instrucciones:
                </p>
                <p class="font-sans text-xl font-normal">
                    {{ sesion.tecnica.instrucciones }}
                </p>
            </section>
        </article>

        <p class="font-bold text-2xl border-b-2">
            Palabras usadas para calificar
        </p>
        <article
            class="text-white rounded-xl grid grid-cols-4 max-sm:grid-cols-1 gap-3 *:bg-gray-500 *:flex *:items-center *:justify-center *:gap-x-2 *:p-4 *:rounded-2xl">
            {% for palabra in palabras %}
            <section>
                <p class="block text-xl antialiased font-medium">
                    {{ palabra.nombre_palabra }}
                </p>
            </section>
            {% endfor %}
        </article>


        <p class="font-bold text-2xl border-b-2">
            Acciones disponibles
        </p>
        <article class="flex flex-wrap gap-10">
            {% if not sesion.activo %}
            <button
                class="ct-btn-start-repition flex-1 uppercase text-lg tracking-wider p-4 border-b-2 active:border-b-0 active:border-t-2 active:border-green-500 border-green-800  transition-all rounded-xl bg-green-600 text-white font-bold disabled:bg-amber-600 flex flex-col justify-center items-center gap-2"
                onclick="startRepetition()">
                Iniciar repetición
                <figure class="w-10">
                    <img src="{% static 'img/giro.svg' %}" alt="flechas girando" class="invert">
                </figure>
            </button>
            {% else %}
            <button
                class="ct-btn-start-repition flex-1 uppercase text-lg tracking-wider p-4 border-b-2 active:border-b-0 active:border-t-2 active:border-orange-500 border-orange-800  transition-all rounded-xl bg-orange-600 text-white font-bold disabled:bg-amber-600 flex flex-col justify-center items-center gap-2">
                Monitorear repetición
                <figure class="w-10">
                    <img src="{% static 'img/monitor.svg' %}" alt="flechas girando" class="invert">
                </figure>
            </button>
            {% endif %}

            <button
                class="flex-1 uppercase text-lg tracking-wider p-4 border-b-2 active:border-b-0 active:border-t-2 active:border-red-500 border-red-800 transition-all rounded-xl bg-red-600 text-white font-bold disabled:bg-amber-600 flex flex-col justify-center items-center gap-2">
                borrar
                <figure class="w-10">
                    <img src="{% static 'img/basura.svg' %}" alt="bote de basura" class="invert">
                </figure>
            </button>
        </article>

        <p class="font-bold text-2xl border-b-2">
            Datos obtenidos
        </p>

        {% if calificaciones.error %}
        <article class="bg-gray-600 p-4 text-white rounded-xl">
            <p class="block font-sans text-xl antialiased font-normal uppercase tracking-wider text-center">
                {{ calificaciones.error }}
            </p>
        </article>
        {% else %}
        <article class="bg-gray-600 p-4 text-white rounded-xl">
        </article>
        {% endif %}
        <form action="" method="post" class="form-action-session hidden">
            {% csrf_token %}
        </form>
    </article>
</article>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/details-session.js' %}"></script>
{% endblock %}

tecnicas/templates/tecnicas/manage_sesions/sesiones-panel.html
{% extends 'tecnicas/layouts/base.html' %}
{% load static %}

{% block title %}Panel Sesiones{% endblock %}

{% block content %}
<article class="w-full flex flex-col justify-center items-center bg-gray-600 mt-10 mb-10">
    <article class="flex flex-col gap-8 bg-gray-400 p-10 rounded-2xl">
        <header class="text-center flex flex-row gap-8 items-center w-full">
            <div class="bg-gray-600 p-4 text-white rounded-xl flex-1">
                <h1 class="font-bold text-2xl">Administra las<br>sesiones sensoriales</h1>
            </div>
            <div class="flex-1">
                <a href="{% url 'cata_system:index' %}"
                    class="text-white bg-blue-600 hover:bg-blue-700 active:outline-none active:ring-4 active:ring-blue-300 font-medium rounded-xl text-xl p-4 text-center uppercase">Panel
                    principal</a>
            </div>
        </header>

        <section class="grid grid-cols-3 gap-4">
            {% for sesion in sessions %}
            <a href="{% url 'cata_system:detalles_sesion' session_code=sesion.codigo_sesion %}"
                class="p-4 bg-gray-200 flex flex-row gap-2 justify-center items-center rounded-lg border-b-4 border-blue-500">
                <div class="text-right *:not-last:mb-2">
                    {% if sesion.nombre_sesion %}
                    <p><b>Nombre:</b></p>
                    {% endif %}
                    <p><b>Código:</b></p>
                    <p><b>Fecha:</b></p>
                    <p><b>Técnica:</b></p>
                    <p><b>Estilo:</b></p>
                </div>
                <div class="*:not-last:mb-2">
                    {% if sesion.nombre_sesion %}
                    <p>{{ sesion.nombre_sesion }}</p>
                    {% endif %}
                    <p>{{ sesion.codigo_sesion }}</p>
                    <p>{{ sesion.fechaCreacion }}</p>
                    <p class="uppercase">{{ sesion.tecnica.tipo_tecnica.nombre_tecnica }}</p>
                    <p class="uppercase">{{ sesion.tecnica.id_estilo.nombre_estilo }}</p>
                </div>
            </a>
            {% endfor %}
        </section>

        <section class="flex justify-center items-center gap-2">
            <button>
                <img class="h-10" src="{% static 'img/less-than.svg' %}" alt="menor que">
            </button>
            <ul class="flex flex-row gap-2">
                <li>1</li>
                <li>2</li>
                <li>3</li>
                <li>. . .</li>
                <li>8</li>
            </ul>
            <button>
                <img class="h-10" src="{% static 'img/greater-than.svg' %}" alt="mayor que">
            </button>
        </section>
    </article>
</article>
{% endblock %}